[build]
  command = "npm install && npm run build"
  functions = "functions"

#[[redirects]]
#  from = "/*"
#  to = "/.netlify/functions/server/:splat"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
